name: SonarQube Scan

on:
  push:
    branches:
      - main
      - develop

jobs: 
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarQube Scanner
        id: cache-sonar
        uses: actions/cache@v3
        with:
          path: ~/.sonar
          key: sonar-${{ runner.os }}

      - name: Run SonarQube Scan
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.host.url=http://your-sonarqube-server:9000 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
